#:kivy 1.0.9

<AlarmClock>:
    Label:
        id: current
        font_size: 70  
        center_x: root.width / 2
        top: root.height / 2 + 20 
    Label:
        id: next
        font_size: 30
        center_x: root.width / 2
        top: root.height / 2 + 90
        
<AlarmPopup>:
    
    Button:
        id: off
        text:"Turn off"
        center_x: root.width / 2
        top: root.height / 2 
        
        
        
